---
- name: Reboot the remote machine
  become: true
  ansible.builtin.shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true
  changed_when: false

- name: Wait for the machine to come up
  become: false
  ansible.builtin.wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: "{{ ansible_port | default(22) }}"
    delay: 10
    timeout: 300
    state: started
  delegate_to: localhost
