---
- name: Install sudo
  become: true
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Allow users in the sudo group to run sudo (with a password)
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^\%sudo'
    line: '%sudo  ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'
    backup: yes
