---
# vim: set ft=yaml.ansible:

### Install Snap Packages
- name: Install Snap packages ({{ install_app_package_set }})
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default('no') }}"
  loop: "{{ install_app_snap_packages }}"
