---
# vim: set ft=yaml.ansible:

### Install traditional apt packages
- name: Install apt packages ({{ package_set }})
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  loop: "{{ apt_packages }}"
