---
- name: Check if Vagrant user exists
  ansible.builtin.command:
    cmd: /usr/bin/getent passwd vagrant | /usr/bin/wc -l | tr -d ''
  register: virtualbox_guest_vbox_vagrant_user_exists
  changed_when: false

- name: Add vagrant user to the VirtualBox group
  become: true
  ansible.builtin.user:
    name: 'vagrant'
    groups: 'vboxsf'
    append: yes
  when: virtualbox_guest_vbox_vagrant_user_exists.stdout == "1"
