---
- name: Check if Vagrant user exists
  command:
    cmd: /usr/bin/getent passwd vagrant | /usr/bin/wc -l | tr -d ''
  register: vbox_vagrant_user_exists
  changed_when: false

- name: Add vagrant user to the VirtualBox group
  become: true
  user:
    name: 'vagrant'
    groups: 'vboxsf'
    append: yes
  when: vbox_vagrant_user_exists.stdout == "1"
