---
- name: Check if Vagrant user exists
  ansible.builtin.shell:
    cmd: /usr/bin/getent passwd vagrant | /usr/bin/wc -l | tr -d ''
  register: virtualbox_guest_vbox_vagrant_user_exists
  changed_when: false

- name: Add vagrant user to the VirtualBox group
  become: true
  ansible.builtin.user:
    name: 'vagrant'
    groups: 'vboxsf'
    append: yes
  when: virtualbox_guest_vbox_vagrant_user_exists.stdout == "1"

- name: Setup vagrant user for passwordless sudo
  become: true
  ansible.builtin.template:
    src: etc-sudoers.d--vagrant.j2
    dest: /etc/sudoers.d/vagrant
    owner: root
    group: root
    mode: 0640
    backup: false
  when: virtualbox_guest_vbox_vagrant_user_exists.stdout == "1"

- name: Add users to the vagrant group (to allow access to vagrant share)
  become: true
  ansible.builtin.user:
    name: '{{ item }}'
    groups: 'vagrant'
    append: yes
  loop: '{{ vagrant_users }}'
  when: virtualbox_guest_vbox_vagrant_user_exists.stdout == "1"
