---
- name: Install ssh
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  with_items:
    - openssh-server
    - openssh-client

- name: Examine if we need to regenerate host keys
  ansible.builtin.stat:
    path: /etc/ssh/ssh_host_keys_regenerated
    get_checksum: false
    get_md5: false
  register: host_keys

- name: Remove Existing Keys
  become: true
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_rsa_key.pub
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_ed25519_key.pub
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ecdsa_key.pub
  when: not host_keys.stat.exists

- name: Regenerate RSA Keys
  become: true
  ansible.builtin.command: /usr/bin/ssh-keygen -t rsa -b 4096 -o -a 100 -f /etc/ssh/ssh_host_rsa_key -N ''
  args:
    creates: /etc/ssh/ssh_host_rsa_key
  when: not host_keys.stat.exists

- name: Regenerate ed25519 Key
  become: true
  ansible.builtin.command: /usr/bin/ssh-keygen -t ed25519 -o -a 100 -f /etc/ssh/ssh_host_ed25519_key -N ''
  args:
    creates: /etc/ssh/ssh_host_ed25519_key
  when: not host_keys.stat.exists

- name: Regenerate ecdsa Key
  become: true
  ansible.builtin.command: /usr/bin/ssh-keygen -t ecdsa -b 521 -o -a 100 -f /etc/ssh/ssh_host_ecdsa_key -N ''
  args:
    creates: /etc/ssh/ssh_host_ecdsa_key
  when: not host_keys.stat.exists

- name: Write Regenerate File
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_host_keys_regenerated
    line: 'Host keys regenerated.'
    state: present
    create: yes
    owner: root
    group: root
    mode: '0644'
  when: not host_keys.stat.exists

- name: Remove outdated host keys
  become: true
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_dsa_key.pub

- name: Copy ssh_config
  become: true
  ansible.builtin.template:
    src: etc-ssh--ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy sshd_config
  become: true
  ansible.builtin.template:
    src: etc-ssh--sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart ssh

- name: Start and enable the ssh service
  become: true
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: yes
