---
- name: Setup APT defaults
  ansible.builtin.import_tasks: apt-defaults.yml

- name: Setup APT Sources
  ansible.builtin.import_tasks: apt-sources.yml

- name: Update the package cache (forced)
  become: true
  ansible.builtin.apt:
    update_cache: yes
    update_cache_retries: 10
    update_cache_retry_max_delay: 10
  changed_when: false
