---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ./molecule/lint
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:latest}
    privileged: true
    command: ${MOLECULE_COMMAND:-"sleep infinity"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
