---
- name: Install popularity contest (enroll requested)
  become: true
  apt:
    name: popularity-contest
  when: enroll_in_popularity_contest

- name: Copy popularity contest config (enroll requested)
  become: true
  template:
    src: etc--popularity-contest.conf.j2
    dest: /etc/popularity-contest.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: enroll_in_popularity_contest

- name: Remove popularity contest (enroll not requested)
  become: true
  apt:
    name: popularity-contest
  when: not enroll_in_popularity_contest
