---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ./molecule/lint
platforms:
  - name: instance-ubuntu-lts
    image: brennanfee/docker-ubuntu-latest-systemd
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: instance-ubuntu-rolling
    image: brennanfee/docker-ubuntu-rolling-systemd
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: instance-debian-stable
    image: brennanfee/docker-debian-stable-systemd
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: instance-debian-testing
    image: brennanfee/docker-debian-testing-systemd
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    host_vars:
      instance-debian-stable:
        apt_edition: stable
      instance-debian-testing:
        apt_edition: testing
verifier:
  name: ansible
