---
- name: Update the package cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade the packages
  become: true
  ansible.builtin.apt:
    upgrade: '{{ apt_upgrade_level | default(safe) }}'
