---
- name: Verify popularity_contest Role
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Verify package is installed
      ansible.builtin.assert:
        that:
          - "'popularity-contest' in ansible_facts.packages"

    - name: Config file should be present
      ansible.builtin.lineinfile:
        path: /etc/popularity-contest.conf
        line: "# Config file for Debian's popularity-contest package."
        backup: no
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)
