---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ./molecule/lint
platforms:
  - name: instance
    image: brennanfee/docker-${MOLECULE_DISTRO:-ubuntu-latest}-systemd
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
