---
# vim: set ft=yaml.ansible:

# TODO: Learn nftables and do all this with that instead of ufw

- name: Install Firewall Tools
  ansible.builtin.apt:
    state: present
    name: ufw

- name: Default Firewall Log Level
  community.general.ufw:
    logging: medium

- name: Default Firewall Outgoing Rule
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Default Firewall Incoming Rule
  community.general.ufw:
    default: deny
    direction: incoming

- name: Add Rule To Allow Incoming SSH
  community.general.ufw:
    rule: limit
    name: OpenSSH

- name: Enable The Firewall
  community.general.ufw:
    state: enabled
