---
- name: Verify allow_sudo Role
  hosts: all
  gather_facts: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Verify package is installed
      ansible.builtin.assert:
        that:
          - "'sudo' in ansible_facts.packages"

    - name: Sudoers has sudo group set up
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "%sudo  ALL=(ALL:ALL) ALL"
        backup: no
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)
