---
- name: Create destination directory if not present
  become: true
  ansible.builtin.file:
    path: "/usr/share/fonts/{{ font_folder | default ('ansible') }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Check if font already exists
  ansible.builtin.stat:
    path: "/usr/share/fonts/{{ font_folder | default ('ansible') }}/{{ font_file }}"
    get_checksum: false
    get_md5: false
  register: font_info

- name: Install the font {{ font_file }}
  become: true
  ansible.builtin.get_url:
    url: "{{ font_url }}"
    dest: "/usr/share/fonts/{{ font_folder | default ('ansible') }}/{{ font_file }}"
    owner: root
    group: root
    mode: 0644
  when: not font_info.stat.exists
  notify: Regenerate Font Cache
