---
- name: Install fonts from packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ font_packages }}"

- name: Install fonts from URL
  ansible.builtin.include_tasks:
    file: install-font-from-url.yml
    apply:
      font_url: "{{ item.url }}"
      font_file: "{{ item.file }}"
      font_folder: "{{ item.folder | default('ansible') }}"
  with_items: "{{ url_fonts }}"
