---
# vim: set ft=yaml.ansible:

- name: Install Timesyncd
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - systemd-timesyncd

- name: Set the time zone
  become: true
  community.general.timezone:
    name: "{{ desired_time_zone | default('America/Chicago', true) }}"
    hwclock: UTC

- name: Setup time sync settings
  become: true
  ansible.builtin.template:
    src: etc-systemd--timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart timesyncd

- name: Start and enable the time sync service
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd.service
    state: started
    enabled: true
