---
- name: Converge
  hosts: all

  roles:
    - upgrade
    - allow_sudo
    - ssh
    - { role: time, desired_time_zone: 'Europe/Berlin' }
    - { role: apt_configuration, apt_proxy_url: 'http://192.168.10.20:3142' }
