---
# vim: set ft=yaml.ansible:

- name: Prepare
  hosts: all

  tasks:
    - name: Update the package cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
