---
### Install traditional apt packages
- name: Install apt packages ({{ package_set }})
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ apt_packages }}"

### Install deb files
- name: Install deb packages ({{ package_set }})
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
  with_items: "{{ deb_packages }}"

### Install Flatpak Packages
- name: Install Flatpak packages ({{ package_set }})
  become: true
  community.general.flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote or 'flathub' }}"
    method: "{{ item.method or 'system' }}"
  with_items: "{{ flatpak_packages }}"

### Install Snap Packages
- name: Install Snap packages ({{ package_set }})
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic or 'no' }}"
  with_items: "{{ snap_packages }}"
