---
### Install apt keys
- name: Setup new apt signing key
  become: true
  manage_apt_key:
    input_key_file: "{{ item.input_key_file }}"
    output_key_file: "{{ item.output_key_file }}"
  loop: "{{ apt_keys }}"
