---
### Install Snap Packages
- name: Install Snap packages ({{ package_set }})
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default('no') }}"
  with_items: "{{ snap_packages }}"
