---
- name: Verify time Role
  hosts: all
  gather_facts: false

# US/Central
# Europe/Berlin

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Verify tzdata package is installed
      ansible.builtin.assert:
        that:
          - "'tzdata' in ansible_facts.packages"

# TODO: Remove this and merge it with the check above after next Debian stable release
    - name: Verify systemd-timesyncd package is installed
      ansible.builtin.assert:
        that:
          - "'systemd-timesyncd' in ansible_facts.packages"
      when: apt_edition is undefined or apt_edition != 'stable'

    - name: Read current time zone
      ansible.builtin.shell: cat /etc/timezone
      changed_when: false
      register: current_time_zone

    - name: Assert we have the correct Timezone
      ansible.builtin.assert:
        that: current_time_zone.stdout == 'Europe/Berlin'

    - name: Timesyncd config file should be managed by Ansible
      ansible.builtin.lineinfile:
        path: /etc/systemd/timesyncd.conf
        line: "## Ansible managed: Do NOT edit this file manually!"
        backup: no
      check_mode: yes
      register: conf
      failed_when: (conf is changed) or (conf is failed)

    - name: Timesyncd service is started and enabled
      ansible.builtin.service:
        name: systemd-timesyncd.service
        state: started
        enabled: yes
      check_mode: yes
      register: svc
      failed_when: (svc is changed) or (svc is failed)
